version: 2
sources:
  - name: ads
    schema: "{{ 'main' if target.type == 'duckdb' else target.schema }}"
    tables:
      - name: campaigns
      - name: impressions
      - name: clicks
      - name: conversions
