version: 2
sources:
  - name: game
    schema: "{{ 'main' if target.type == 'duckdb' else target.schema }}"
    tables:
      - name: players
      - name: sessions
      - name: events
      - name: purchases
      - name: levels
