p03_iot:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "data/warehouse.duckdb"
      threads: 16
    postgres:
      type: postgres
      host: 0.0.0.0
      user: runner
      password: password
      port: 5432
      dbname: benchmark
      schema: synth_one_p03_iot
      threads: 16
