tpcds:
  outputs:
    dev:
      type: duckdb
      path: tpcds.duckdb
      threads: 4
    postgres:
      type: postgres
      host: 0.0.0.0
      user: runner
      password: password
      port: 5432
      dbname: benchmark
      schema: tpcds
      threads: 4
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
