name: 'p08_healthcare'
version: '1.0.0'
config-version: 2
profile: 'p08_healthcare'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  p08_healthcare:
    layer_1:
      +materialized: view
      stg_claims:
        +materialized: table
    layer_2:
      +materialized: view
    layer_3:
      +materialized: view
    layer_4:
      +materialized: view
    layer_5:
      +materialized: view
    layer_6:
      +materialized: view
    layer_7:
      +materialized: table
