version: 2
sources:
  - name: sc
    schema: "{{ 'main' if target.type == 'duckdb' else target.schema }}"
    tables:
      - name: suppliers
      - name: warehouses
      - name: shipments
      - name: inventory
      - name: purchase_orders
