version: 2

models:
  - name: dept_salary_stats
    tests:
      - not_empty
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [dept_name, division]
    columns:
      - name: dept_name
        tests:
          - dbt_utils.at_least_one
      - name: division
        tests:
          - dbt_utils.at_least_one
      - name: headcount
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 0
      - name: avg_base
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 50000
              max_value: 350000
      - name: stddev_base
        tests:
          - dbt_utils.at_least_one
      - name: total_comp_spend
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 0

  - name: employee_profile
    tests:
      - not_empty
      - unique:
          column_name: emp_id
    columns:
      - name: emp_id
        tests:
          - dbt_utils.at_least_one
      - name: full_name
        tests:
          - dbt_utils.at_least_one
      - name: dept_name
        tests:
          - dbt_utils.at_least_one
      - name: division
        tests:
          - dbt_utils.at_least_one
      - name: location
        tests:
          - dbt_utils.at_least_one
      - name: gender
        tests:
          - dbt_utils.at_least_one
      - name: employment_type
        tests:
          - dbt_utils.at_least_one
      - name: tenure_years
        tests:
          - dbt_utils.at_least_one
      - name: is_active
        tests:
          - dbt_utils.at_least_one
      - name: base_salary
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 50000
              max_value: 350000
      - name: total_comp
        tests:
          - dbt_utils.at_least_one
      - name: avg_perf_score
        tests:
          - dbt_utils.at_least_one
      - name: review_count
        tests:
          - dbt_utils.at_least_one
      - name: total_leave_days
        tests:
          - dbt_utils.at_least_one
      - name: sick_days
        tests:
          - dbt_utils.at_least_one
      - name: perf_band
        tests:
          - dbt_utils.at_least_one
          - accepted_values:
              values: ['High', 'Meets', 'Below']
