p09_gaming:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "data/warehouse.duckdb"
      threads: 4
    postgres:
      type: postgres
      host: 0.0.0.0
      user: runner
      password: password
      port: 5432
      dbname: benchmark
      schema: synth_multi_p09_gaming
      threads: 4
