version: 2

sources:
  - name: tpch
    schema: "{{ 'main' if target.type == 'duckdb' else target.schema }}"
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
