version: 2

models:
  - name: category_deep_dive
    tests:
      - not_empty
    columns:
      - name: category_id
        tests:
          - unique
          - dbt_utils.at_least_one
      - name: category_name
        tests:
          - dbt_utils.at_least_one
      - name: category_revenue_rank
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 1
      - name: top10_products
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: top10_revenue
        tests:
          - dbt_utils.at_least_one
      - name: avg_rating
        tests:
          - dbt_utils.at_least_one
      - name: avg_pos_pct
        tests:
          - dbt_utils.at_least_one

  - name: cohort_revenue
    tests:
      - not_empty
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [signup_year, country, value_segment]
    columns:
      - name: signup_year
        tests:
          - dbt_utils.at_least_one
      - name: country
        tests:
          - dbt_utils.at_least_one
          - accepted_values:
              values: ['US','CA','GB','DE','FR','AU','JP','BR','IN','MX','IT','ES','NL','SE','KR']
      - name: value_segment
        tests:
          - dbt_utils.at_least_one
          - accepted_values:
              values: ['VIP','High','Mid','Low']
      - name: customers
        tests:
          - dbt_utils.at_least_one
          - dbt_utils.accepted_range:
              min_value: 1
      - name: cohort_revenue
        tests:
          - dbt_utils.at_least_one
      - name: avg_aov
        tests:
          - dbt_utils.at_least_one
