version: 2
sources:
  - name: hr
    schema: "{{ 'main' if target.type == 'duckdb' else target.schema }}"
    tables:
      - name: departments
      - name: employees
      - name: salaries
      - name: performance_reviews
      - name: leave_requests
