name: 'p06_saas'
version: '1.0.0'
config-version: 2
profile: 'p06_saas'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  p06_saas:
    layer_1:
      +materialized: view
    layer_2:
      +materialized: view
    layer_3:
      +materialized: view
    layer_4:
      +materialized: view
    layer_5:
      +materialized: view
    layer_6:
      +materialized: table
